<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.3 Review of Statistical Concepts | Simulation Modeling using the Kotlin Simulation Library (KSL)</title>
  <meta name="description" content="A book that illustrates the basics of using the KSL. The output format for this book is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="3.3 Review of Statistical Concepts | Simulation Modeling using the Kotlin Simulation Library (KSL)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A book that illustrates the basics of using the KSL. The output format for this book is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.3 Review of Statistical Concepts | Simulation Modeling using the Kotlin Simulation Library (KSL)" />
  
  <meta name="twitter:description" content="A book that illustrates the basics of using the KSL. The output format for this book is bookdown::gitbook." />
  

<meta name="author" content="Manuel D. Rossetti" />


<meta name="date" content="2025-09-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ssMC.html"/>
<link rel="next" href="craps.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Simulation Modeling using the Kotlin Simulation Library (KSL)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="release-history.html"><a href="release-history.html"><i class="fa fa-check"></i>Release History</a></li>
<li class="chapter" data-level="" data-path="ksl-project-page.html"><a href="ksl-project-page.html"><i class="fa fa-check"></i>KSL Project Page</a></li>
<li class="chapter" data-level="" data-path="book-support-files.html"><a href="book-support-files.html"><i class="fa fa-check"></i>Book Support Files</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="" data-path="intended-audience.html"><a href="intended-audience.html"><i class="fa fa-check"></i>Intended Audience</a></li>
<li class="chapter" data-level="" data-path="organization-of-the-book.html"><a href="organization-of-the-book.html"><i class="fa fa-check"></i>Organization of the Book</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="ch1.html"><a href="ch1.html"><i class="fa fa-check"></i><b>1</b> Simulation Modeling</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simulation-modeling.html"><a href="simulation-modeling.html"><i class="fa fa-check"></i><b>1.1</b> Simulation Modeling</a></li>
<li class="chapter" data-level="1.2" data-path="why-simulate.html"><a href="why-simulate.html"><i class="fa fa-check"></i><b>1.2</b> Why Simulate?</a></li>
<li class="chapter" data-level="1.3" data-path="types-of-systems-and-simulation-models.html"><a href="types-of-systems-and-simulation-models.html"><i class="fa fa-check"></i><b>1.3</b> Types of Systems and Simulation Models</a></li>
<li class="chapter" data-level="1.4" data-path="simulation-descriptive-or-prescriptive-modeling.html"><a href="simulation-descriptive-or-prescriptive-modeling.html"><i class="fa fa-check"></i><b>1.4</b> Simulation: Descriptive or Prescriptive Modeling?</a></li>
<li class="chapter" data-level="1.5" data-path="randomness-in-simulation.html"><a href="randomness-in-simulation.html"><i class="fa fa-check"></i><b>1.5</b> Randomness in Simulation</a></li>
<li class="chapter" data-level="1.6" data-path="simulation-languages.html"><a href="simulation-languages.html"><i class="fa fa-check"></i><b>1.6</b> Simulation Languages</a></li>
<li class="chapter" data-level="1.7" data-path="ch1secsimMeth.html"><a href="ch1secsimMeth.html"><i class="fa fa-check"></i><b>1.7</b> Simulation Methodology</a></li>
<li class="chapter" data-level="1.8" data-path="overview-of-the-kotlin-simulation-library.html"><a href="overview-of-the-kotlin-simulation-library.html"><i class="fa fa-check"></i><b>1.8</b> Overview of the Kotlin Simulation Library</a></li>
<li class="chapter" data-level="1.9" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>1.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch2rng.html"><a href="ch2rng.html"><i class="fa fa-check"></i><b>2</b> Modeling Randomness</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch2generator.html"><a href="ch2generator.html"><i class="fa fa-check"></i><b>2.1</b> Random Number Generator</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="ch2generator.html"><a href="ch2generator.html#ch2randompkg"><i class="fa fa-check"></i><b>2.1.1</b> Random Package</a></li>
<li class="chapter" data-level="2.1.2" data-path="ch2generator.html"><a href="ch2generator.html#ch2creatingStreams"><i class="fa fa-check"></i><b>2.1.2</b> Creating and Using Streams</a></li>
<li class="chapter" data-level="2.1.3" data-path="ch2generator.html"><a href="ch2generator.html#ch2crn"><i class="fa fa-check"></i><b>2.1.3</b> Common Random Numbers</a></li>
<li class="chapter" data-level="2.1.4" data-path="ch2generator.html"><a href="ch2generator.html#ch2antitheticStreams"><i class="fa fa-check"></i><b>2.1.4</b> Creating and Using Antithetic Streams</a></li>
<li class="chapter" data-level="2.1.5" data-path="ch2generator.html"><a href="ch2generator.html#ch2rnFAQ"><i class="fa fa-check"></i><b>2.1.5</b> Frequently Asked Questions about Random Numbers</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="rvg.html"><a href="rvg.html"><i class="fa fa-check"></i><b>2.2</b> Random Variate Generation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rvg.html"><a href="rvg.html#basic-random-variate-generation"><i class="fa fa-check"></i><b>2.2.1</b> Basic Random Variate Generation</a></li>
<li class="chapter" data-level="2.2.2" data-path="rvg.html"><a href="rvg.html#rvg_dists"><i class="fa fa-check"></i><b>2.2.2</b> Continuous and Discrete Random Variables</a></li>
<li class="chapter" data-level="2.2.3" data-path="rvg.html"><a href="rvg.html#rvguse"><i class="fa fa-check"></i><b>2.2.3</b> Creating and Using Random Variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="rvg.html"><a href="rvg.html#functions-of-random-variables"><i class="fa fa-check"></i><b>2.2.4</b> Functions of Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="probModels.html"><a href="probModels.html"><i class="fa fa-check"></i><b>2.3</b> Probability Distribution Models</a></li>
<li class="chapter" data-level="2.4" data-path="distFitting.html"><a href="distFitting.html"><i class="fa fa-check"></i><b>2.4</b> Distribution Fitting Using the KSL</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="distFitting.html"><a href="distFitting.html#estimating-distribution-parameters"><i class="fa fa-check"></i><b>2.4.1</b> Estimating Distribution Parameters</a></li>
<li class="chapter" data-level="2.4.2" data-path="distFitting.html"><a href="distFitting.html#continuous-distribution-recommendation-framework"><i class="fa fa-check"></i><b>2.4.2</b> Continuous Distribution Recommendation Framework</a></li>
<li class="chapter" data-level="2.4.3" data-path="distFitting.html"><a href="distFitting.html#discrete-distribution-framework"><i class="fa fa-check"></i><b>2.4.3</b> Discrete Distribution Framework</a></li>
<li class="chapter" data-level="2.4.4" data-path="distFitting.html"><a href="distFitting.html#pdfmexamples"><i class="fa fa-check"></i><b>2.4.4</b> Illustrative Examples from Appendix @ref(appidm)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>2.5</b> Summary</a></li>
<li class="chapter" data-level="2.6" data-path="exercises-1.html"><a href="exercises-1.html"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mcm.html"><a href="mcm.html"><i class="fa fa-check"></i><b>3</b> Monte Carlo Methods</a>
<ul>
<li class="chapter" data-level="3.1" data-path="kslStatistics.html"><a href="kslStatistics.html"><i class="fa fa-check"></i><b>3.1</b> Collecting Statistics</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="kslStatistics.html"><a href="kslStatistics.html#creating-and-using-a-statistic"><i class="fa fa-check"></i><b>3.1.1</b> Creating and Using a Statistic</a></li>
<li class="chapter" data-level="3.1.2" data-path="kslStatistics.html"><a href="kslStatistics.html#histFreq"><i class="fa fa-check"></i><b>3.1.2</b> Histograms and Frequencies</a></li>
<li class="chapter" data-level="3.1.3" data-path="kslStatistics.html"><a href="kslStatistics.html#ch3batchStats"><i class="fa fa-check"></i><b>3.1.3</b> Batch Statistics</a></li>
<li class="chapter" data-level="3.1.4" data-path="kslStatistics.html"><a href="kslStatistics.html#ch3StatSummary"><i class="fa fa-check"></i><b>3.1.4</b> Statistics Summary</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ssMC.html"><a href="ssMC.html"><i class="fa fa-check"></i><b>3.2</b> Simple Monte Carlo Integration</a></li>
<li class="chapter" data-level="3.3" data-path="ch3StatReview.html"><a href="ch3StatReview.html"><i class="fa fa-check"></i><b>3.3</b> Review of Statistical Concepts</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="ch3StatReview.html"><a href="ch3StatReview.html#point-estimates-and-confidence-intervals"><i class="fa fa-check"></i><b>3.3.1</b> Point Estimates and Confidence Intervals</a></li>
<li class="chapter" data-level="3.3.2" data-path="ch3StatReview.html"><a href="ch3StatReview.html#ch3SampleSize"><i class="fa fa-check"></i><b>3.3.2</b> Sample Size Determination</a></li>
<li class="chapter" data-level="3.3.3" data-path="ch3StatReview.html"><a href="ch3StatReview.html#determining-the-sample-size-for-a-monte-carlo-simulation-experiment"><i class="fa fa-check"></i><b>3.3.3</b> Determining the Sample Size for a Monte Carlo Simulation Experiment</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="craps.html"><a href="craps.html"><i class="fa fa-check"></i><b>3.4</b> Simulating the Game of Craps</a></li>
<li class="chapter" data-level="3.5" data-path="the-news-vendor-problem.html"><a href="the-news-vendor-problem.html"><i class="fa fa-check"></i><b>3.5</b> The News Vendor Problem</a></li>
<li class="chapter" data-level="3.6" data-path="ch3InsProcess.html"><a href="ch3InsProcess.html"><i class="fa fa-check"></i><b>3.6</b> A Simple Inspection Process</a></li>
<li class="chapter" data-level="3.7" data-path="ch3SAN.html"><a href="ch3SAN.html"><i class="fa fa-check"></i><b>3.7</b> Stochastic Activity Networks</a></li>
<li class="chapter" data-level="3.8" data-path="mcmExperiments.html"><a href="mcmExperiments.html"><i class="fa fa-check"></i><b>3.8</b> Monte-Carlo Experiments</a></li>
<li class="chapter" data-level="3.9" data-path="summary-1.html"><a href="summary-1.html"><i class="fa fa-check"></i><b>3.9</b> Summary</a></li>
<li class="chapter" data-level="3.10" data-path="exercises-2.html"><a href="exercises-2.html"><i class="fa fa-check"></i><b>3.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introDEDS.html"><a href="introDEDS.html"><i class="fa fa-check"></i><b>4</b> Introduction to Discrete Event Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introDEDSdeds.html"><a href="introDEDSdeds.html"><i class="fa fa-check"></i><b>4.1</b> Discrete-Event Dynamic Systems</a></li>
<li class="chapter" data-level="4.2" data-path="HowDEDSClockWorks.html"><a href="HowDEDSClockWorks.html"><i class="fa fa-check"></i><b>4.2</b> How the Discrete-Event Clock Works</a></li>
<li class="chapter" data-level="4.3" data-path="QHandExample.html"><a href="QHandExample.html"><i class="fa fa-check"></i><b>4.3</b> Simulating a Queueing System By Hand</a></li>
<li class="chapter" data-level="4.4" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html"><i class="fa fa-check"></i><b>4.4</b> Modeling DEDS in the KSL</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html#event-scheduling"><i class="fa fa-check"></i><b>4.4.1</b> Event Scheduling</a></li>
<li class="chapter" data-level="4.4.2" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html#introDEDSschedExamples"><i class="fa fa-check"></i><b>4.4.2</b> Simple Event Scheduling Examples</a></li>
<li class="chapter" data-level="4.4.3" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html#introDEDSUpDown"><i class="fa fa-check"></i><b>4.4.3</b> Up and Down Component Example</a></li>
<li class="chapter" data-level="4.4.4" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html#introDEDSPharmacy"><i class="fa fa-check"></i><b>4.4.4</b> Modeling a Simple Queueing System</a></li>
<li class="chapter" data-level="4.4.5" data-path="introDEDSdedsKSL.html"><a href="introDEDSdedsKSL.html#more-details-about-the-pharmacy-model-implementation"><i class="fa fa-check"></i><b>4.4.5</b> More Details About the Pharmacy Model Implementation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html"><i class="fa fa-check"></i><b>4.5</b> Enhancing the Drive Through Pharmacy Model</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html#modeling-a-simple-resource"><i class="fa fa-check"></i><b>4.5.1</b> Modeling a Simple Resource</a></li>
<li class="chapter" data-level="4.5.2" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html#modeling-a-queue-with-statistical-collection"><i class="fa fa-check"></i><b>4.5.2</b> Modeling a Queue with Statistical Collection</a></li>
<li class="chapter" data-level="4.5.3" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html#modeling-a-repeating-event-pattern"><i class="fa fa-check"></i><b>4.5.3</b> Modeling a Repeating Event Pattern</a></li>
<li class="chapter" data-level="4.5.4" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html#collecting-more-detailed-statistics"><i class="fa fa-check"></i><b>4.5.4</b> Collecting More Detailed Statistics</a></li>
<li class="chapter" data-level="4.5.5" data-path="enhancing-the-drive-through-pharmacy-model.html"><a href="enhancing-the-drive-through-pharmacy-model.html#implementing-the-enhanced-pharmacy-model"><i class="fa fa-check"></i><b>4.5.5</b> Implementing the Enhanced Pharmacy Model</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="DTPExpanded.html"><a href="DTPExpanded.html"><i class="fa fa-check"></i><b>4.6</b> More Drive Through Fun</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="DTPExpanded.html"><a href="DTPExpanded.html#modeling-a-resource-with-a-waiting-line"><i class="fa fa-check"></i><b>4.6.1</b> Modeling a Resource with a Waiting Line</a></li>
<li class="chapter" data-level="4.6.2" data-path="DTPExpanded.html"><a href="DTPExpanded.html#modeling-the-tandem-queue-of-example-refexmexch4tandemq"><i class="fa fa-check"></i><b>4.6.2</b> Modeling the Tandem Queue of Example @ref(exm:exCh4TandemQ)</a></li>
<li class="chapter" data-level="4.6.3" data-path="DTPExpanded.html"><a href="DTPExpanded.html#modeling-with-the-station-package"><i class="fa fa-check"></i><b>4.6.3</b> Modeling with the Station Package</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="introDEDSSummary.html"><a href="introDEDSSummary.html"><i class="fa fa-check"></i><b>4.7</b> Summary</a></li>
<li class="chapter" data-level="4.8" data-path="exercises-3.html"><a href="exercises-3.html"><i class="fa fa-check"></i><b>4.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simoa.html"><a href="simoa.html"><i class="fa fa-check"></i><b>5</b> Analyzing and Accessing Simulation Output</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simoadatatypes.html"><a href="simoadatatypes.html"><i class="fa fa-check"></i><b>5.1</b> Types of Statistical Variables</a></li>
<li class="chapter" data-level="5.2" data-path="simoasimtypes.html"><a href="simoasimtypes.html"><i class="fa fa-check"></i><b>5.2</b> Types of Simulation With Respect To Output Analysis</a></li>
<li class="chapter" data-level="5.3" data-path="simoafinhorizon.html"><a href="simoafinhorizon.html"><i class="fa fa-check"></i><b>5.3</b> Analysis of Finite Horizon Simulations</a></li>
<li class="chapter" data-level="5.4" data-path="simoafinhorizonex.html"><a href="simoafinhorizonex.html"><i class="fa fa-check"></i><b>5.4</b> Capturing Output for a Simple Finite Horizon Simulation</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="simoafinhorizonex.html"><a href="simoafinhorizonex.html#simoaCapture"><i class="fa fa-check"></i><b>5.4.1</b> KSL Functionality for Capturing Statistical Results</a></li>
<li class="chapter" data-level="5.4.2" data-path="simoafinhorizonex.html"><a href="simoafinhorizonex.html#additional-remarks"><i class="fa fa-check"></i><b>5.4.2</b> Additional Remarks</a></li>
<li class="chapter" data-level="5.4.3" data-path="simoafinhorizonex.html"><a href="simoafinhorizonex.html#querying-the-ksl-database"><i class="fa fa-check"></i><b>5.4.3</b> Querying the KSL Database</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="simoaseqsampling.html"><a href="simoaseqsampling.html"><i class="fa fa-check"></i><b>5.5</b> Sequential Sampling for Finite Horizon Simulations</a></li>
<li class="chapter" data-level="5.6" data-path="simoainfhorizon.html"><a href="simoainfhorizon.html"><i class="fa fa-check"></i><b>5.6</b> Analysis of Infinite Horizon Simulations</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="simoainfhorizon.html"><a href="simoainfhorizon.html#simoainfhorizoninitialbias"><i class="fa fa-check"></i><b>5.6.1</b> Assessing the Effect of Initial Conditions</a></li>
<li class="chapter" data-level="5.6.2" data-path="simoainfhorizon.html"><a href="simoainfhorizon.html#simoainfhorizonrepDeletion"><i class="fa fa-check"></i><b>5.6.2</b> Performing the Method of Replication-Deletion</a></li>
<li class="chapter" data-level="5.6.3" data-path="simoainfhorizon.html"><a href="simoainfhorizon.html#simoainfhorizonbatchmeans"><i class="fa fa-check"></i><b>5.6.3</b> The Method of Batch Means</a></li>
<li class="chapter" data-level="5.6.4" data-path="simoainfhorizon.html"><a href="simoainfhorizon.html#simoainfhorizonjslbatching"><i class="fa fa-check"></i><b>5.6.4</b> Performing the Method of Batch Means</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="simoacomparingSystems.html"><a href="simoacomparingSystems.html"><i class="fa fa-check"></i><b>5.7</b> Comparing System Configurations</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="simoacomparingSystems.html"><a href="simoacomparingSystems.html#simoacomparingSystems:two"><i class="fa fa-check"></i><b>5.7.1</b> Comparing Two Systems</a></li>
<li class="chapter" data-level="5.7.2" data-path="simoacomparingSystems.html"><a href="simoacomparingSystems.html#simoacomparingSystemsMCB"><i class="fa fa-check"></i><b>5.7.2</b> Concepts for Comparing Systems</a></li>
<li class="chapter" data-level="5.7.3" data-path="simoacomparingSystems.html"><a href="simoacomparingSystems.html#multiple-comparison-with-the-best-procedures-mcb"><i class="fa fa-check"></i><b>5.7.3</b> Multiple Comparison with the Best Procedures (MCB)</a></li>
<li class="chapter" data-level="5.7.4" data-path="simoacomparingSystems.html"><a href="simoacomparingSystems.html#ch5Screening"><i class="fa fa-check"></i><b>5.7.4</b> Screening Procedures</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="ch5Scenarios.html"><a href="ch5Scenarios.html"><i class="fa fa-check"></i><b>5.8</b> Simulating Many Scenarios</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="ch5Scenarios.html"><a href="ch5Scenarios.html#controlAntns"><i class="fa fa-check"></i><b>5.8.1</b> Control Annotations</a></li>
<li class="chapter" data-level="5.8.2" data-path="ch5Scenarios.html"><a href="ch5Scenarios.html#rvParameters"><i class="fa fa-check"></i><b>5.8.2</b> Random Variable Parameters</a></li>
<li class="chapter" data-level="5.8.3" data-path="ch5Scenarios.html"><a href="ch5Scenarios.html#kslScenarios"><i class="fa fa-check"></i><b>5.8.3</b> Setting Up and Running Multiple Scenarios</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="simoasummary.html"><a href="simoasummary.html"><i class="fa fa-check"></i><b>5.9</b> Summary</a></li>
<li class="chapter" data-level="5.10" data-path="exercises-4.html"><a href="exercises-4.html"><i class="fa fa-check"></i><b>5.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="processview.html"><a href="processview.html"><i class="fa fa-check"></i><b>6</b> Process View Modeling Using the KSL</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch6Entities.html"><a href="ch6Entities.html"><i class="fa fa-check"></i><b>6.1</b> What are Entities?</a></li>
<li class="chapter" data-level="6.2" data-path="pvIntro.html"><a href="pvIntro.html"><i class="fa fa-check"></i><b>6.2</b> The Process View</a></li>
<li class="chapter" data-level="6.3" data-path="understanding-ksl-processes-and-entities.html"><a href="understanding-ksl-processes-and-entities.html"><i class="fa fa-check"></i><b>6.3</b> Understanding KSL Processes and Entities</a></li>
<li class="chapter" data-level="6.4" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html"><i class="fa fa-check"></i><b>6.4</b> Examples of Process Modeling</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html#holding-entities-in-a-queue-holdqueue-class"><i class="fa fa-check"></i><b>6.4.1</b> Holding Entities in a Queue: <code>HoldQueue</code> Class</a></li>
<li class="chapter" data-level="6.4.2" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html#signaling-entities"><i class="fa fa-check"></i><b>6.4.2</b> Signaling Entities</a></li>
<li class="chapter" data-level="6.4.3" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html#understanding-blocking-queues"><i class="fa fa-check"></i><b>6.4.3</b> Understanding Blocking Queues</a></li>
<li class="chapter" data-level="6.4.4" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html#allowing-entities-to-wait-for-a-process"><i class="fa fa-check"></i><b>6.4.4</b> Allowing Entities to Wait for a Process</a></li>
<li class="chapter" data-level="6.4.5" data-path="examples-of-process-modeling.html"><a href="examples-of-process-modeling.html#processinteraction"><i class="fa fa-check"></i><b>6.4.5</b> Process Interaction</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modeling-a-stem-career-mixer.html"><a href="modeling-a-stem-career-mixer.html"><i class="fa fa-check"></i><b>6.5</b> Modeling a STEM Career Mixer</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modeling-a-stem-career-mixer.html"><a href="modeling-a-stem-career-mixer.html#conceptualizing-the-system"><i class="fa fa-check"></i><b>6.5.1</b> Conceptualizing the System</a></li>
<li class="chapter" data-level="6.5.2" data-path="modeling-a-stem-career-mixer.html"><a href="modeling-a-stem-career-mixer.html#implementing-the-stem-mixer-model"><i class="fa fa-check"></i><b>6.5.2</b> Implementing the STEM Mixer Model</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="the-tie-dye-t-shirt-model.html"><a href="the-tie-dye-t-shirt-model.html"><i class="fa fa-check"></i><b>6.6</b> The Tie-Dye T-Shirt Model</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="the-tie-dye-t-shirt-model.html"><a href="the-tie-dye-t-shirt-model.html#ch4:TieDyeTShirtsSub1"><i class="fa fa-check"></i><b>6.6.1</b> Implementing the Tie-Dye T-Shirt Model</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="summary-2.html"><a href="summary-2.html"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
<li class="chapter" data-level="6.8" data-path="exercises-5.html"><a href="exercises-5.html"><i class="fa fa-check"></i><b>6.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch7AdvModeling.html"><a href="ch7AdvModeling.html"><i class="fa fa-check"></i><b>7</b> Advanced Event and Process View Modeling</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modeling-with-processes-and-resources.html"><a href="modeling-with-processes-and-resources.html"><i class="fa fa-check"></i><b>7.1</b> Modeling with Processes and Resources</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="modeling-with-processes-and-resources.html"><a href="modeling-with-processes-and-resources.html#modeling-space-with-resources"><i class="fa fa-check"></i><b>7.1.1</b> Modeling Space with Resources</a></li>
<li class="chapter" data-level="7.1.2" data-path="modeling-with-processes-and-resources.html"><a href="modeling-with-processes-and-resources.html#secResourcePools"><i class="fa fa-check"></i><b>7.1.2</b> Resource Pools</a></li>
<li class="chapter" data-level="7.1.3" data-path="modeling-with-processes-and-resources.html"><a href="modeling-with-processes-and-resources.html#secTestAndRepair"><i class="fa fa-check"></i><b>7.1.3</b> Computer Test and Repair Shop Example</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="modeling-non-stationary-systems.html"><a href="modeling-non-stationary-systems.html"><i class="fa fa-check"></i><b>7.2</b> Modeling Non-Stationary Systems</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="modeling-non-stationary-systems.html"><a href="modeling-non-stationary-systems.html#ch7secNSPP"><i class="fa fa-check"></i><b>7.2.1</b> Non-Stationary Arrival Processes</a></li>
<li class="chapter" data-level="7.2.2" data-path="modeling-non-stationary-systems.html"><a href="modeling-non-stationary-systems.html#modeling-resources-under-non-stationary-conditions"><i class="fa fa-check"></i><b>7.2.2</b> Modeling Resources Under Non-Stationary Conditions</a></li>
<li class="chapter" data-level="7.2.3" data-path="modeling-non-stationary-systems.html"><a href="modeling-non-stationary-systems.html#enhancing-the-stem-career-mixer-model"><i class="fa fa-check"></i><b>7.2.3</b> Enhancing the STEM Career Mixer Model</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="examples-of-advanced-event-models.html"><a href="examples-of-advanced-event-models.html"><i class="fa fa-check"></i><b>7.3</b> Examples of Advanced Event Models</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="examples-of-advanced-event-models.html"><a href="examples-of-advanced-event-models.html#ch6s1sb4sub3"><i class="fa fa-check"></i><b>7.3.1</b> Modeling Balking and Reneging</a></li>
<li class="chapter" data-level="7.3.2" data-path="examples-of-advanced-event-models.html"><a href="examples-of-advanced-event-models.html#rqModel"><i class="fa fa-check"></i><b>7.3.2</b> Modeling a Reorder Point, Reorder Quantity Inventory Policy</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch7VandV.html"><a href="ch7VandV.html"><i class="fa fa-check"></i><b>7.4</b> Applying Queueing Theory Results to Verify and Validate a Simulation</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ch7VandV.html"><a href="ch7VandV.html#analyzing-the-preparation-station"><i class="fa fa-check"></i><b>7.4.1</b> Analyzing the Preparation Station</a></li>
<li class="chapter" data-level="7.4.2" data-path="ch7VandV.html"><a href="ch7VandV.html#analyzing-the-build-lines"><i class="fa fa-check"></i><b>7.4.2</b> Analyzing the Build Lines</a></li>
<li class="chapter" data-level="7.4.3" data-path="ch7VandV.html"><a href="ch7VandV.html#analyzing-the-packaging-station"><i class="fa fa-check"></i><b>7.4.3</b> Analyzing the Packaging Station</a></li>
<li class="chapter" data-level="7.4.4" data-path="ch7VandV.html"><a href="ch7VandV.html#analyzing-the-palletizing-station"><i class="fa fa-check"></i><b>7.4.4</b> Analyzing the Palletizing Station</a></li>
<li class="chapter" data-level="7.4.5" data-path="ch7VandV.html"><a href="ch7VandV.html#analyzing-the-total-system-time"><i class="fa fa-check"></i><b>7.4.5</b> Analyzing the Total System Time</a></li>
<li class="chapter" data-level="7.4.6" data-path="ch7VandV.html"><a href="ch7VandV.html#other-issues-for-verification-and-validation"><i class="fa fa-check"></i><b>7.4.6</b> Other Issues for Verification and Validation</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="summary-3.html"><a href="summary-3.html"><i class="fa fa-check"></i><b>7.5</b> Summary</a></li>
<li class="chapter" data-level="7.6" data-path="exercises-6.html"><a href="exercises-6.html"><i class="fa fa-check"></i><b>7.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chEntityMovement.html"><a href="chEntityMovement.html"><i class="fa fa-check"></i><b>8</b> Modeling Entity Movement</a>
<ul>
<li class="chapter" data-level="8.1" data-path="secRCT.html"><a href="secRCT.html"><i class="fa fa-check"></i><b>8.1</b> Resource Constrained Transfer</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="secRCT.html"><a href="secRCT.html#secTestRepairRCT"><i class="fa fa-check"></i><b>8.1.1</b> Test and Repair with Resource Constrained Transfer</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="movableResources.html"><a href="movableResources.html"><i class="fa fa-check"></i><b>8.2</b> Constrained Transfer with Movable Resources</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="movableResources.html"><a href="movableResources.html#spatial-models"><i class="fa fa-check"></i><b>8.2.1</b> Spatial Models</a></li>
<li class="chapter" data-level="8.2.2" data-path="movableResources.html"><a href="movableResources.html#secMovableResources"><i class="fa fa-check"></i><b>8.2.2</b> Movable Resources</a></li>
<li class="chapter" data-level="8.2.3" data-path="movableResources.html"><a href="movableResources.html#secTQMWM"><i class="fa fa-check"></i><b>8.2.3</b> Tandem Queue Model With Movement</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="secTestAndRepairMovableResources.html"><a href="secTestAndRepairMovableResources.html"><i class="fa fa-check"></i><b>8.3</b> Modeling the Test and Repair System with Movable Resources</a></li>
<li class="chapter" data-level="8.4" data-path="secConveyors.html"><a href="secConveyors.html"><i class="fa fa-check"></i><b>8.4</b> Modeling Systems with Conveyors</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="secConveyors.html"><a href="secConveyors.html#ksl-conveyor-constructs"><i class="fa fa-check"></i><b>8.4.1</b> KSL Conveyor Constructs</a></li>
<li class="chapter" data-level="8.4.2" data-path="secConveyors.html"><a href="secConveyors.html#tandem-queue-system-with-conveyors"><i class="fa fa-check"></i><b>8.4.2</b> Tandem Queue System with Conveyors</a></li>
<li class="chapter" data-level="8.4.3" data-path="secConveyors.html"><a href="secConveyors.html#secTestAndRepairConveyors"><i class="fa fa-check"></i><b>8.4.3</b> Test and Repair via Conveyors</a></li>
<li class="chapter" data-level="8.4.4" data-path="secConveyors.html"><a href="secConveyors.html#secMiscConveyor"><i class="fa fa-check"></i><b>8.4.4</b> Miscellaneous Concepts in Conveyor Modeling</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="summary-of-new-concepts.html"><a href="summary-of-new-concepts.html"><i class="fa fa-check"></i><b>8.5</b> Summary of New Concepts</a></li>
<li class="chapter" data-level="8.6" data-path="exercises-7.html"><a href="exercises-7.html"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch9AdvMC.html"><a href="ch9AdvMC.html"><i class="fa fa-check"></i><b>9</b> Advanced Monte Carlo Methods</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch9BootStrapping.html"><a href="ch9BootStrapping.html"><i class="fa fa-check"></i><b>9.1</b> Bootstrap Methods</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="ch9BootStrapping.html"><a href="ch9BootStrapping.html#bootstrapping-using-the-ksl"><i class="fa fa-check"></i><b>9.1.1</b> Bootstrapping Using the KSL</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ch9VRTs.html"><a href="ch9VRTs.html"><i class="fa fa-check"></i><b>9.2</b> Variance Reduction Techniques</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ch9VRTs.html"><a href="ch9VRTs.html#common-random-numbers-crn"><i class="fa fa-check"></i><b>9.2.1</b> Common Random Numbers (CRN)</a></li>
<li class="chapter" data-level="9.2.2" data-path="ch9VRTs.html"><a href="ch9VRTs.html#antithetic-variates-av"><i class="fa fa-check"></i><b>9.2.2</b> Antithetic Variates (AV)</a></li>
<li class="chapter" data-level="9.2.3" data-path="ch9VRTs.html"><a href="ch9VRTs.html#indirect-estimation"><i class="fa fa-check"></i><b>9.2.3</b> Indirect Estimation</a></li>
<li class="chapter" data-level="9.2.4" data-path="ch9VRTs.html"><a href="ch9VRTs.html#control-variates-cv"><i class="fa fa-check"></i><b>9.2.4</b> Control Variates (CV)</a></li>
<li class="chapter" data-level="9.2.5" data-path="ch9VRTs.html"><a href="ch9VRTs.html#stratified-and-post-stratified-sampling"><i class="fa fa-check"></i><b>9.2.5</b> Stratified and Post Stratified Sampling</a></li>
<li class="chapter" data-level="9.2.6" data-path="ch9VRTs.html"><a href="ch9VRTs.html#conditional-expectation-ce"><i class="fa fa-check"></i><b>9.2.6</b> Conditional Expectation (CE)</a></li>
<li class="chapter" data-level="9.2.7" data-path="ch9VRTs.html"><a href="ch9VRTs.html#importance-sampling-is"><i class="fa fa-check"></i><b>9.2.7</b> Importance Sampling (IS)</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ch9GMVRVs.html"><a href="ch9GMVRVs.html"><i class="fa fa-check"></i><b>9.3</b> Generating Multi-Variate and Correlated Random Variates</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ch9GMVRVs.html"><a href="ch9GMVRVs.html#generating-from-a-bivariate-normal-distribution"><i class="fa fa-check"></i><b>9.3.1</b> Generating from a Bivariate Normal Distribution</a></li>
<li class="chapter" data-level="9.3.2" data-path="ch9GMVRVs.html"><a href="ch9GMVRVs.html#copulas-and-multi-variate-generation-methods"><i class="fa fa-check"></i><b>9.3.2</b> Copulas and Multi-variate Generation Methods</a></li>
<li class="chapter" data-level="9.3.3" data-path="ch9GMVRVs.html"><a href="ch9GMVRVs.html#autocorrelated-generation"><i class="fa fa-check"></i><b>9.3.3</b> Autocorrelated Generation</a></li>
<li class="chapter" data-level="9.3.4" data-path="ch9GMVRVs.html"><a href="ch9GMVRVs.html#ch9MCMC"><i class="fa fa-check"></i><b>9.3.4</b> Introduction to Markov Chain Monte Carlo Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="summary-4.html"><a href="summary-4.html"><i class="fa fa-check"></i><b>9.4</b> Summary</a></li>
<li class="chapter" data-level="9.5" data-path="exercises-8.html"><a href="exercises-8.html"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch10eo.html"><a href="ch10eo.html"><i class="fa fa-check"></i><b>10</b> Experimental Design and Simulation Optimization Methods</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch10doe.html"><a href="ch10doe.html"><i class="fa fa-check"></i><b>10.1</b> Experimental Design Methods</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="ch10doe.html"><a href="ch10doe.html#ch10factors"><i class="fa fa-check"></i><b>10.1.1</b> Defining Factors</a></li>
<li class="chapter" data-level="10.1.2" data-path="ch10doe.html"><a href="ch10doe.html#ch10designs"><i class="fa fa-check"></i><b>10.1.2</b> Defining Experimental Designs</a></li>
<li class="chapter" data-level="10.1.3" data-path="ch10doe.html"><a href="ch10doe.html#ch10exp"><i class="fa fa-check"></i><b>10.1.3</b> Executing a Designed Experiment</a></li>
<li class="chapter" data-level="10.1.4" data-path="ch10doe.html"><a href="ch10doe.html#ch10analysis"><i class="fa fa-check"></i><b>10.1.4</b> Analyzing a Designed Experiment</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="ch10simOpt.html"><a href="ch10simOpt.html"><i class="fa fa-check"></i><b>10.2</b> Simulation Optimization Methods</a></li>
<li class="chapter" data-level="10.3" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html"><i class="fa fa-check"></i><b>10.3</b> Defining Simulation Optimization Problems</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html#specifying-penalty-functions"><i class="fa fa-check"></i><b>10.3.1</b> Specifying Penalty Functions</a></li>
<li class="chapter" data-level="10.3.2" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html#inputvariables"><i class="fa fa-check"></i><b>10.3.2</b> Defining Input Variables</a></li>
<li class="chapter" data-level="10.3.3" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html#linear-and-functional-constraints"><i class="fa fa-check"></i><b>10.3.3</b> Linear and Functional Constraints</a></li>
<li class="chapter" data-level="10.3.4" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html#response-constraints"><i class="fa fa-check"></i><b>10.3.4</b> Response Constraints</a></li>
<li class="chapter" data-level="10.3.5" data-path="ch10ProbDefn.html"><a href="ch10ProbDefn.html#ch10ProbDefnExample"><i class="fa fa-check"></i><b>10.3.5</b> Setting Up a Problem Definition</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="representing-the-simulation-oracle.html"><a href="representing-the-simulation-oracle.html"><i class="fa fa-check"></i><b>10.4</b> Representing the Simulation Oracle</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="representing-the-simulation-oracle.html"><a href="representing-the-simulation-oracle.html#requesting-simulation-evaluations"><i class="fa fa-check"></i><b>10.4.1</b> Requesting Simulation Evaluations</a></li>
<li class="chapter" data-level="10.4.2" data-path="representing-the-simulation-oracle.html"><a href="representing-the-simulation-oracle.html#representing-model-inputs"><i class="fa fa-check"></i><b>10.4.2</b> Representing Model Inputs</a></li>
<li class="chapter" data-level="10.4.3" data-path="representing-the-simulation-oracle.html"><a href="representing-the-simulation-oracle.html#representing-model-outputs"><i class="fa fa-check"></i><b>10.4.3</b> Representing Model Outputs</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="characterizing-simulation-optimization-algorithms.html"><a href="characterizing-simulation-optimization-algorithms.html"><i class="fa fa-check"></i><b>10.5</b> Characterizing Simulation Optimization Algorithms</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="characterizing-simulation-optimization-algorithms.html"><a href="characterizing-simulation-optimization-algorithms.html#structure-of-the-iterative-process"><i class="fa fa-check"></i><b>10.5.1</b> Structure of the Iterative Process</a></li>
<li class="chapter" data-level="10.5.2" data-path="characterizing-simulation-optimization-algorithms.html"><a href="characterizing-simulation-optimization-algorithms.html#solver-plug-in-behavior"><i class="fa fa-check"></i><b>10.5.2</b> Solver Plug-in Behavior</a></li>
<li class="chapter" data-level="10.5.3" data-path="characterizing-simulation-optimization-algorithms.html"><a href="characterizing-simulation-optimization-algorithms.html#miscellaneous-concepts-in-the-solver-class"><i class="fa fa-check"></i><b>10.5.3</b> Miscellaneous Concepts in the <code>Solver</code> Class</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="implemented-solvers.html"><a href="implemented-solvers.html"><i class="fa fa-check"></i><b>10.6</b> Implemented Solvers</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="implemented-solvers.html"><a href="implemented-solvers.html#simulated-annealing"><i class="fa fa-check"></i><b>10.6.1</b> Simulated Annealing</a></li>
<li class="chapter" data-level="10.6.2" data-path="implemented-solvers.html"><a href="implemented-solvers.html#cross-entropy"><i class="fa fa-check"></i><b>10.6.2</b> Cross Entropy</a></li>
<li class="chapter" data-level="10.6.3" data-path="implemented-solvers.html"><a href="implemented-solvers.html#r-spline"><i class="fa fa-check"></i><b>10.6.3</b> R-SPLINE</a></li>
<li class="chapter" data-level="10.6.4" data-path="implemented-solvers.html"><a href="implemented-solvers.html#randomized-restart-solvers"><i class="fa fa-check"></i><b>10.6.4</b> Randomized Restart Solvers</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="secApplySolver.html"><a href="secApplySolver.html"><i class="fa fa-check"></i><b>10.7</b> Using a Solver on a Problem</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="secApplySolver.html"><a href="secApplySolver.html#applyCE"><i class="fa fa-check"></i><b>10.7.1</b> Illustrating the Cross-Entropy Solver</a></li>
<li class="chapter" data-level="10.7.2" data-path="secApplySolver.html"><a href="secApplySolver.html#illustrating-simulated-annealing-with-random-restarts"><i class="fa fa-check"></i><b>10.7.2</b> Illustrating Simulated Annealing with Random Restarts</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="summary-5.html"><a href="summary-5.html"><i class="fa fa-check"></i><b>10.8</b> Summary</a></li>
<li class="chapter" data-level="10.9" data-path="exercises-9.html"><a href="exercises-9.html"><i class="fa fa-check"></i><b>10.9</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appRNRV.html"><a href="appRNRV.html"><i class="fa fa-check"></i><b>A</b> Generating Pseudo-Random Numbers and Random Variates</a>
<ul>
<li class="chapter" data-level="A.1" data-path="appRNRVPRN.html"><a href="appRNRVPRN.html"><i class="fa fa-check"></i><b>A.1</b> Pseudo Random Numbers</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="appRNRVPRN.html"><a href="appRNRVPRN.html#appRNRVRNGs"><i class="fa fa-check"></i><b>A.1.1</b> Random Number Generators</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="appRNRVs.html"><a href="appRNRVs.html"><i class="fa fa-check"></i><b>A.2</b> Generating Random Variates from Distributions</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="appRNRVs.html"><a href="appRNRVs.html#inverse-transform-method"><i class="fa fa-check"></i><b>A.2.1</b> Inverse Transform Method</a></li>
<li class="chapter" data-level="A.2.2" data-path="appRNRVs.html"><a href="appRNRVs.html#convolution"><i class="fa fa-check"></i><b>A.2.2</b> Convolution</a></li>
<li class="chapter" data-level="A.2.3" data-path="appRNRVs.html"><a href="appRNRVs.html#acceptancerejection"><i class="fa fa-check"></i><b>A.2.3</b> Acceptance/Rejection</a></li>
<li class="chapter" data-level="A.2.4" data-path="appRNRVs.html"><a href="appRNRVs.html#AppRNRVsubsecMTSRV"><i class="fa fa-check"></i><b>A.2.4</b> Mixture Distributions, Truncated Distributions, and Shifted Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="summary-6.html"><a href="summary-6.html"><i class="fa fa-check"></i><b>A.3</b> Summary</a></li>
<li class="chapter" data-level="A.4" data-path="exercises-10.html"><a href="exercises-10.html"><i class="fa fa-check"></i><b>A.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="appidm.html"><a href="appidm.html"><i class="fa fa-check"></i><b>B</b> Probability Distribution Modeling</a>
<ul>
<li class="chapter" data-level="B.1" data-path="appidmsecrvPD.html"><a href="appidmsecrvPD.html"><i class="fa fa-check"></i><b>B.1</b> Random Variables and Probability Distributions</a></li>
<li class="chapter" data-level="B.2" data-path="appidmsecMDD.html"><a href="appidmsecMDD.html"><i class="fa fa-check"></i><b>B.2</b> Modeling with Discrete Distributions</a></li>
<li class="chapter" data-level="B.3" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html"><i class="fa fa-check"></i><b>B.3</b> Fitting Discrete Distributions</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#AppDisFitPoissonFit"><i class="fa fa-check"></i><b>B.3.1</b> Fitting a Poisson Distribution</a></li>
<li class="chapter" data-level="B.3.2" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#visualizing-the-data"><i class="fa fa-check"></i><b>B.3.2</b> Visualizing the Data</a></li>
<li class="chapter" data-level="B.3.3" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#estimating-the-rate-parameter-for-the-poisson-distribution"><i class="fa fa-check"></i><b>B.3.3</b> Estimating the Rate Parameter for the Poisson Distribution</a></li>
<li class="chapter" data-level="B.3.4" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#chi-squared-goodness-of-fit-test-for-poisson-distribution"><i class="fa fa-check"></i><b>B.3.4</b> Chi-Squared Goodness of Fit Test for Poisson Distribution</a></li>
<li class="chapter" data-level="B.3.5" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#subsubchisqGOF"><i class="fa fa-check"></i><b>B.3.5</b> Chi-Squared Goodness of Fit Test</a></li>
<li class="chapter" data-level="B.3.6" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#using-the-fitdistrplus-r-package-on-discrete-data"><i class="fa fa-check"></i><b>B.3.6</b> Using the fitdistrplus R Package on Discrete Data</a></li>
<li class="chapter" data-level="B.3.7" data-path="appidmsecfitDiscrete.html"><a href="appidmsecfitDiscrete.html#fitting-a-discrete-empirical-distribution"><i class="fa fa-check"></i><b>B.3.7</b> Fitting a Discrete Empirical Distribution</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="appidmsecMCD.html"><a href="appidmsecMCD.html"><i class="fa fa-check"></i><b>B.4</b> Modeling with Continuous Distributions</a></li>
<li class="chapter" data-level="B.5" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html"><i class="fa fa-check"></i><b>B.5</b> Fitting Continuous Distributions</a>
<ul>
<li class="chapter" data-level="B.5.1" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#appidmsubsecvisualizedata"><i class="fa fa-check"></i><b>B.5.1</b> Visualizing the Data</a></li>
<li class="chapter" data-level="B.5.2" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#appidmsubsecstatsdata"><i class="fa fa-check"></i><b>B.5.2</b> Statistically Summarize the Data</a></li>
<li class="chapter" data-level="B.5.3" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#appidmsubsechypothDist"><i class="fa fa-check"></i><b>B.5.3</b> Hypothesizing and Testing a Distribution</a></li>
<li class="chapter" data-level="B.5.4" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>B.5.4</b> Kolmogorov-Smirnov Test</a></li>
<li class="chapter" data-level="B.5.5" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#appidmsubsecvisFit"><i class="fa fa-check"></i><b>B.5.5</b> Visualizing the Fit</a></li>
<li class="chapter" data-level="B.5.6" data-path="appidmsecfitContinuous.html"><a href="appidmsecfitContinuous.html#appidms2sb3"><i class="fa fa-check"></i><b>B.5.6</b> Using the Input Analyzer</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="appdistfittestU01.html"><a href="appdistfittestU01.html"><i class="fa fa-check"></i><b>B.6</b> Testing Uniform (0,1) Pseudo-Random Numbers</a>
<ul>
<li class="chapter" data-level="B.6.1" data-path="appdistfittestU01.html"><a href="appdistfittestU01.html#chi-squared-goodness-of-fit-tests-for-pseudo-random-numbers"><i class="fa fa-check"></i><b>B.6.1</b> Chi-Squared Goodness of Fit Tests for Pseudo-Random Numbers</a></li>
<li class="chapter" data-level="B.6.2" data-path="appdistfittestU01.html"><a href="appdistfittestU01.html#higher-dimensional-chi-squared-test"><i class="fa fa-check"></i><b>B.6.2</b> Higher Dimensional Chi-Squared Test</a></li>
<li class="chapter" data-level="B.6.3" data-path="appdistfittestU01.html"><a href="appdistfittestU01.html#kolmogorov-smirnov-test-for-pseudo-random-numbers"><i class="fa fa-check"></i><b>B.6.3</b> Kolmogorov-Smirnov Test for Pseudo-Random Numbers</a></li>
<li class="chapter" data-level="B.6.4" data-path="appdistfittestU01.html"><a href="appdistfittestU01.html#testing-for-independence-and-patterns-in-pseudo-random-numbers"><i class="fa fa-check"></i><b>B.6.4</b> Testing for Independence and Patterns in Pseudo-Random Numbers</a></li>
</ul></li>
<li class="chapter" data-level="B.7" data-path="appdistfitidms2sb4.html"><a href="appdistfitidms2sb4.html"><i class="fa fa-check"></i><b>B.7</b> Additional Distribution Modeling Concepts</a></li>
<li class="chapter" data-level="B.8" data-path="appidmSummary.html"><a href="appidmSummary.html"><i class="fa fa-check"></i><b>B.8</b> Summary</a></li>
<li class="chapter" data-level="B.9" data-path="exercises-11.html"><a href="exercises-11.html"><i class="fa fa-check"></i><b>B.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="appqtAndInvT.html"><a href="appqtAndInvT.html"><i class="fa fa-check"></i><b>C</b> Queueing Theory</a>
<ul>
<li class="chapter" data-level="C.1" data-path="appqts1.html"><a href="appqts1.html"><i class="fa fa-check"></i><b>C.1</b> Single Line Queueing Stations</a>
<ul>
<li class="chapter" data-level="C.1.1" data-path="appqts1.html"><a href="appqts1.html#queueing-notation"><i class="fa fa-check"></i><b>C.1.1</b> Queueing Notation</a></li>
<li class="chapter" data-level="C.1.2" data-path="appqts1.html"><a href="appqts1.html#littles-formula"><i class="fa fa-check"></i><b>C.1.2</b> Little’s Formula</a></li>
<li class="chapter" data-level="C.1.3" data-path="appqts1.html"><a href="appqts1.html#appqts1sb1"><i class="fa fa-check"></i><b>C.1.3</b> Deriving Formulas for Markovian Single Queue Systems</a></li>
</ul></li>
<li class="chapter" data-level="C.2" data-path="appqts1sb2.html"><a href="appqts1sb2.html"><i class="fa fa-check"></i><b>C.2</b> Examples and Applications of Queueing Analysis</a>
<ul>
<li class="chapter" data-level="C.2.1" data-path="appqts1sb2.html"><a href="appqts1sb2.html#infinite-queue-examples"><i class="fa fa-check"></i><b>C.2.1</b> Infinite Queue Examples</a></li>
<li class="chapter" data-level="C.2.2" data-path="appqts1sb2.html"><a href="appqts1sb2.html#finite-queue-examples"><i class="fa fa-check"></i><b>C.2.2</b> Finite Queue Examples</a></li>
</ul></li>
<li class="chapter" data-level="C.3" data-path="appqts1sb3.html"><a href="appqts1sb3.html"><i class="fa fa-check"></i><b>C.3</b> Non-Markovian Queues and Approximations</a></li>
<li class="chapter" data-level="C.4" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html"><i class="fa fa-check"></i><b>C.4</b> Summary of Queueing Formulas</a>
<ul>
<li class="chapter" data-level="C.4.1" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mm1-queue"><i class="fa fa-check"></i><b>C.4.1</b> M/M/1 Queue</a></li>
<li class="chapter" data-level="C.4.2" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mmc-queue"><i class="fa fa-check"></i><b>C.4.2</b> M/M/c Queue</a></li>
<li class="chapter" data-level="C.4.3" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mmck-queue"><i class="fa fa-check"></i><b>C.4.3</b> M/M/c/k Queue</a></li>
<li class="chapter" data-level="C.4.4" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mgcc-queue"><i class="fa fa-check"></i><b>C.4.4</b> M/G/c/c Queue</a></li>
<li class="chapter" data-level="C.4.5" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mm1k-queue"><i class="fa fa-check"></i><b>C.4.5</b> M/M/1/k Queue</a></li>
<li class="chapter" data-level="C.4.6" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mmck-queue-1"><i class="fa fa-check"></i><b>C.4.6</b> M/M/c/k Queue</a></li>
<li class="chapter" data-level="C.4.7" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mm1kk-queue"><i class="fa fa-check"></i><b>C.4.7</b> M/M/1/k/k Queue</a></li>
<li class="chapter" data-level="C.4.8" data-path="appqtsecformulas.html"><a href="appqtsecformulas.html#mmckk-queue"><i class="fa fa-check"></i><b>C.4.8</b> M/M/c/k/k Queue</a></li>
</ul></li>
<li class="chapter" data-level="C.5" data-path="exercises-12.html"><a href="exercises-12.html"><i class="fa fa-check"></i><b>C.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="appUtilities.html"><a href="appUtilities.html"><i class="fa fa-check"></i><b>D</b> KSL Utility Packages</a>
<ul>
<li class="chapter" data-level="D.1" data-path="the-outputdirectory-class-and-ksl-object.html"><a href="the-outputdirectory-class-and-ksl-object.html"><i class="fa fa-check"></i><b>D.1</b> The <code>OutputDirectory</code> Class and <code>KSL</code> Object</a></li>
<li class="chapter" data-level="D.2" data-path="logging-options.html"><a href="logging-options.html"><i class="fa fa-check"></i><b>D.2</b> Logging Options</a></li>
<li class="chapter" data-level="D.3" data-path="the-kslfileutil-object.html"><a href="the-kslfileutil-object.html"><i class="fa fa-check"></i><b>D.3</b> The <code>KSLFileUtil</code> Object</a></li>
<li class="chapter" data-level="D.4" data-path="appDCSVEtc.html"><a href="appDCSVEtc.html"><i class="fa fa-check"></i><b>D.4</b> CSV, Excel, and Tabular Data Files</a></li>
<li class="chapter" data-level="D.5" data-path="dfUtil.html"><a href="dfUtil.html"><i class="fa fa-check"></i><b>D.5</b> The <code>DataFrameUtil</code> Object</a></li>
<li class="chapter" data-level="D.6" data-path="ksl-database-utilities.html"><a href="ksl-database-utilities.html"><i class="fa fa-check"></i><b>D.6</b> KSL Database Utilities</a></li>
<li class="chapter" data-level="D.7" data-path="appUtilitiesArrays.html"><a href="appUtilitiesArrays.html"><i class="fa fa-check"></i><b>D.7</b> Array Utilities</a></li>
<li class="chapter" data-level="D.8" data-path="appPlotting.html"><a href="appPlotting.html"><i class="fa fa-check"></i><b>D.8</b> KSL Plotting Utilities</a></li>
<li class="chapter" data-level="D.9" data-path="appUtilitiesMisc.html"><a href="appUtilitiesMisc.html"><i class="fa fa-check"></i><b>D.9</b> Miscellaneous Utilities</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="distributions.html"><a href="distributions.html"><i class="fa fa-check"></i><b>E</b> Distributions</a>
<ul>
<li class="chapter" data-level="E.1" data-path="appDiscreteDistributions.html"><a href="appDiscreteDistributions.html"><i class="fa fa-check"></i><b>E.1</b> Discrete Distrbutions</a></li>
<li class="chapter" data-level="E.2" data-path="appContinuousDistributions.html"><a href="appContinuousDistributions.html"><i class="fa fa-check"></i><b>E.2</b> Continuous Distrbutions</a></li>
</ul></li>
<li class="chapter" data-level="F" data-path="appStatTables.html"><a href="appStatTables.html"><i class="fa fa-check"></i><b>F</b> Statistical Tables</a></li>
<li class="chapter" data-level="G" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>G</b> References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Simulation Modeling using the Kotlin Simulation Library (KSL)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch3StatReview" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Review of Statistical Concepts<a href="ch3StatReview.html#ch3StatReview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simulation models that have been illustrated have
estimated the quantity of interest with a point estimate (i.e.
<span class="math inline">\(\bar{X}\)</span>). For example, in the previous section, we can easily compute the true area under the curve as <span class="math inline">\(4.6\bar{6}\)</span>; however, the point estimate returned by the simulation was a value of 4.781, based on 100 samples. Thus, there is
sampling error in our estimate. The key question examined in this
section is how to control the sampling error in a simulation experiment.
The approach that we will take is to determine the number of samples so
that we can have high confidence in our point estimate. In order to
address these issues, we need to review some basic statistical concepts in order to understand the meaning of sampling error.</p>
<div id="point-estimates-and-confidence-intervals" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Point Estimates and Confidence Intervals<a href="ch3StatReview.html#point-estimates-and-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(x_{i}\)</span> represent the <span class="math inline">\(i^{th}\)</span> observations in a sample, <span class="math inline">\(x_{1}, x_{2},...x_{n}\)</span> of size <span class="math inline">\(n\)</span>. Represent the random variables in the sample as <span class="math inline">\(X_{1}, X_{2},...X_{n}\)</span>. The
random variables form a random sample, if 1) the <span class="math inline">\(X_{i}\)</span> are independent
random variables and 2) every <span class="math inline">\(X_{i}\)</span> has the same probability
distribution. Let’s assume that these two assumptions have been
established. Denote the unknown cumulative distribution function of <span class="math inline">\(X\)</span>
as <span class="math inline">\(F(x)\)</span> and define the unknown expected value and variance of <span class="math inline">\(X\)</span> with
<span class="math inline">\(E[X] = \mu\)</span> and <span class="math inline">\(Var[X] = \sigma^2\)</span>, respectively.</p>
<p>A statistic is any function of the random variables in a sample. Any
statistic that is used to estimate an unknown quantity based on the
sample is called an estimator. What would be a good estimator for the
quantity <span class="math inline">\(E[X] = \mu\)</span>? Without going into the details of the meaning of
statistical goodness, one should remember that the sample average is
generally a good estimator for <span class="math inline">\(E[X] = \mu\)</span>. Define the sample average
as follows:</p>
<p><span class="math display" id="eq:sampleAvg">\[\begin{equation}
\bar{X} = \frac{1}{n}\sum_{i=1}^{n}X_i
  \tag{3.3}
\end{equation}\]</span></p>
<p>Notice that <span class="math inline">\(\bar{X}\)</span> is a function of the
random variables in the sample and therefore it is also a random
variable. This makes <span class="math inline">\(\bar{X}\)</span> a statistic, since it is a function of the
random variables in the sample.</p>
<p>Any random variable has a corresponding probability distribution. The
probability distribution associated with a statistic is called its
sampling distribution. The sampling distribution of a statistic can be
used to form a confidence interval on the point estimate associated with
the statistic. The point estimate is simply the value obtained from the
statistic once the data has been realized. The point estimate for the
sample average is computed from the sample:</p>
<p><span class="math display">\[\bar{x} = \frac{1}{n}\sum_{i=1}^{n}x_i\]</span></p>
<p>A confidence interval expresses a degree of certainty associated with a
point estimate. A specific confidence interval does not imply that the
parameter <span class="math inline">\(\mu\)</span> is inside the interval. In fact, the true parameter is
either in the interval or it is not within the interval. Instead you
should think about the confidence level <span class="math inline">\(1-\alpha\)</span> as an assurance about
the procedure used to compute the interval. That is, a confidence
interval procedure ensures that if a large number of confidence
intervals are computed each based on <span class="math inline">\(n\)</span> samples, then the proportion of
the confidence intervals that actually contain the true value of <span class="math inline">\(\mu\)</span>
should be close to <span class="math inline">\(1-\alpha\)</span>. The value <span class="math inline">\(\alpha\)</span> represents risk that
the confidence interval procedure will produce a specific interval that
does not contain the true parameter value. Any one particular confidence
interval will either contain the true parameter of interest or it will
not. Since you do not know the true value, you can use the confidence
interval to assess the risk of making a bad decision based on the point
estimate. You can be confident in your decision making or conversely
know that you are taking a risk of <span class="math inline">\(\alpha\)</span> of making a bad decision.
Think of <span class="math inline">\(\alpha\)</span> as the risk that using the confidence interval
procedure will get you fired. If we know the sampling distribution of
the statistic, then we can form a confidence interval procedure.</p>
<p>Under the assumption that the sample size is large enough such that the
distribution of <span class="math inline">\(\bar{X}\)</span> is normally distributed then you can form an
approximate confidence interval on the point estimate, <span class="math inline">\(\bar{x}\)</span>.
Assuming that the sample variance:</p>
<p><span class="math display" id="eq:sampleVar">\[\begin{equation}
S^{2}(n) = \frac{1}{n-1}\sum_{i=1}^{n}(X_i-\bar{X})^2
  \tag{3.4}
\end{equation}\]</span></p>
<p>is a good estimator for <span class="math inline">\(Var[X] = \sigma^2\)</span>, then a <span class="math inline">\((1-\alpha)100\%\)</span>
two-sided confidence interval estimate for <span class="math inline">\(\mu\)</span> is:</p>
<p><span class="math display" id="eq:ci">\[\begin{equation}
\bar{x} \pm t_{1-(\alpha/2), n-1} \dfrac{s}{\sqrt{n}}
  \tag{3.5}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(t_{p, \nu}\)</span> is the <span class="math inline">\(100p\)</span> percentage
point of the Student t-distribution with <span class="math inline">\(\nu\)</span> degrees of freedom. The spreadsheet
function T.INV(p, degrees freedom) computes the <em>left-tailed</em>
Student-t distribution value for a given probability and degrees of
freedom. That is, <span class="math inline">\(t_{p, \nu} = T.INV(p,\nu)\)</span>. The spreadsheet tab labeled <em>Student-t</em> in
the spreadsheet that accompanies this chapter illustrates functions related to the Student-t distribution. Thus, in order to compute <span class="math inline">\(t_{1-(\alpha/2), n-1}\)</span>, use the following formula:</p>
<p><span class="math display">\[t_{1-(\alpha/2), n-1} = T.INV(1-(\alpha/2),n-1)\]</span>
The T.INV.2T(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\nu\)</span>) spreadsheet function directly computes the <em>upper two-tailed</em> value. That is,</p>
<p><span class="math display">\[
t_{1-(\alpha/2), n-1} =T.INV.2T(\alpha, n-1)
\]</span>
Within the statistical package R, this computation is straight-forward by using the <span class="math inline">\(t_{p, n} = qt(p,n)\)</span> function.</p>
<p><span class="math display">\[
t_{p, n} = qt(p,n)
\]</span></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="ch3StatReview.html#cb80-1" tabindex="-1"></a><span class="co">#&#39;qt(0.975, 5)</span></span>
<span id="cb80-2"><a href="ch3StatReview.html#cb80-2" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 2.570582</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="ch3StatReview.html#cb82-1" tabindex="-1"></a><span class="co">#&#39; set alpha</span></span>
<span id="cb82-2"><a href="ch3StatReview.html#cb82-2" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb82-3"><a href="ch3StatReview.html#cb82-3" tabindex="-1"></a><span class="co">#&#39;qt(1-(alpha/2, 5)</span></span>
<span id="cb82-4"><a href="ch3StatReview.html#cb82-4" tabindex="-1"></a><span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>(alpha<span class="sc">/</span><span class="dv">2</span>),<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 2.570582</code></pre>
<p>Using the KSL, we can compute the quantile of the Student-T distribution via the following:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode kt"><code class="sourceCode kotlin"><span id="cb84-1"><a href="ch3StatReview.html#cb84-1" tabindex="-1"></a><span class="kw">fun</span> <span class="fu">main</span><span class="op">(){</span></span>
<span id="cb84-2"><a href="ch3StatReview.html#cb84-2" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">level</span> <span class="op">=</span> <span class="fl">0.95</span></span>
<span id="cb84-3"><a href="ch3StatReview.html#cb84-3" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">dof</span> <span class="op">=</span> <span class="fl">5.0</span></span>
<span id="cb84-4"><a href="ch3StatReview.html#cb84-4" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">alpha</span> <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> level</span>
<span id="cb84-5"><a href="ch3StatReview.html#cb84-5" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">p</span> <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="fl">2.0</span></span>
<span id="cb84-6"><a href="ch3StatReview.html#cb84-6" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">t</span><span class="op">:</span> <span class="kw">Double</span> <span class="op">=</span> StudentT<span class="op">.</span>invCDF<span class="op">(</span>dof<span class="op">,</span> p<span class="op">)</span></span>
<span id="cb84-7"><a href="ch3StatReview.html#cb84-7" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;p = </span><span class="ss">$p</span><span class="st"> dof = </span><span class="ss">$dof</span><span class="st"> t-value = </span><span class="ss">$t</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb84-8"><a href="ch3StatReview.html#cb84-8" tabindex="-1"></a><span class="op">}</span></span></code></pre></div>
<p>With results:</p>
<pre><code>p = 0.975 dof = 5.0 t-value = 2.5705818445939186</code></pre>
</div>
<div id="ch3SampleSize" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Sample Size Determination<a href="ch3StatReview.html#ch3SampleSize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The confidence interval for a point estimator can serve as the basis for
determining how many observations to have in the sample. From Equation <a href="ch3StatReview.html#eq:ci">(3.5)</a>, the quantity:</p>
<p><span class="math display" id="eq:hw">\[\begin{equation}
h = t_{1-(\alpha/2), n-1} \dfrac{s}{\sqrt{n}}
  \tag{3.6}
\end{equation}\]</span></p>
<p>is called the half-width of the confidence interval. You can place a
bound, <span class="math inline">\(\epsilon\)</span>, on the half-width by picking a sample size that satisfies:</p>
<p><span class="math display" id="eq:hwBound">\[\begin{equation}
h = t_{1-(\alpha/2), n-1} \dfrac{s}{\sqrt{n}} \leq \epsilon
  \tag{3.7}
\end{equation}\]</span></p>
<p>We call <span class="math inline">\(\epsilon\)</span> the margin of error for the bound. Unfortunately, <span class="math inline">\(t_{1-(\alpha/2), n-1}\)</span> depends on <span class="math inline">\(n\)</span>, and thus
Equation <a href="ch3StatReview.html#eq:hwBound">(3.7)</a> is an iterative equation. That is, you must try different values of <span class="math inline">\(n\)</span> until the condition is satisfied. Within this text, we call this method for determining the sample size the <em>Student-T iterative method</em>.</p>
<p>Alternatively, the required sample size can be approximated using the
normal distribution. Solving Equation <a href="ch3StatReview.html#eq:hwBound">(3.7)</a> for <span class="math inline">\(n\)</span> yields:</p>
<p><span class="math display">\[n \geq \left(\dfrac{t_{1-(\alpha/2), n-1} \; s}{\epsilon}\right)^2\]</span></p>
<p>As <span class="math inline">\(n\)</span> gets large, <span class="math inline">\(t_{1-(\alpha/2), n-1}\)</span> converges to the
<span class="math inline">\(100(1-(\alpha/2))\)</span> percentage point of the standard normal distribution
<span class="math inline">\(z_{1-(\alpha/2)}\)</span>. This yields the following approximation:</p>
<p><span class="math display" id="eq:zSampleSize">\[\begin{equation}
n \geq \left(\dfrac{z_{1-(\alpha/2)} s}{\epsilon}\right)^2
  \tag{3.8}
\end{equation}\]</span></p>
<p>Within this text, we refer to this method for determining the sample size as the <em>normal approximation</em> method. This approximation generally works well for large <span class="math inline">\(n\)</span>, say <span class="math inline">\(n &gt; 50\)</span>. Both of these methods require an initial value for the standard deviation. This computation is implemented in the function, <code>estimateSampleSize</code> of the <code>Statisitic</code> class’s companion object.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode kt"><code class="sourceCode kotlin"><span id="cb86-1"><a href="ch3StatReview.html#cb86-1" tabindex="-1"></a>        <span class="co">/**</span></span>
<span id="cb86-2"><a href="ch3StatReview.html#cb86-2" tabindex="-1"></a><span class="co">         * Estimate the sample size based on a normal approximation</span></span>
<span id="cb86-3"><a href="ch3StatReview.html#cb86-3" tabindex="-1"></a><span class="co">         *</span></span>
<span id="cb86-4"><a href="ch3StatReview.html#cb86-4" tabindex="-1"></a><span class="co">         * @param desiredHW the desired half-width (must be bigger than 0)</span></span>
<span id="cb86-5"><a href="ch3StatReview.html#cb86-5" tabindex="-1"></a><span class="co">         * @param stdDev    the standard deviation (must be bigger than or equal to 0)</span></span>
<span id="cb86-6"><a href="ch3StatReview.html#cb86-6" tabindex="-1"></a><span class="co">         * @param level     the confidence level (must be between 0 and 1)</span></span>
<span id="cb86-7"><a href="ch3StatReview.html#cb86-7" tabindex="-1"></a><span class="co">         * @return the estimated sample size</span></span>
<span id="cb86-8"><a href="ch3StatReview.html#cb86-8" tabindex="-1"></a><span class="co">         */</span></span>
<span id="cb86-9"><a href="ch3StatReview.html#cb86-9" tabindex="-1"></a>        <span class="kw">fun</span> <span class="fu">estimateSampleSize</span><span class="op">(</span><span class="va">desiredHW</span><span class="op">:</span> <span class="dt">Double</span><span class="op">,</span> <span class="va">stdDev</span><span class="op">:</span> <span class="dt">Double</span><span class="op">,</span> <span class="va">level</span><span class="op">:</span> <span class="dt">Double</span><span class="op">):</span> <span class="dt">Long</span> <span class="op">{</span></span>
<span id="cb86-10"><a href="ch3StatReview.html#cb86-10" tabindex="-1"></a>            require<span class="op">(</span>desiredHW <span class="op">&gt;</span> <span class="fl">0.0</span><span class="op">)</span> <span class="op">{</span> <span class="st">&quot;The desired half-width must be &gt; 0&quot;</span> <span class="op">}</span></span>
<span id="cb86-11"><a href="ch3StatReview.html#cb86-11" tabindex="-1"></a>            require<span class="op">(</span>stdDev <span class="op">&gt;=</span> <span class="fl">0.0</span><span class="op">)</span> <span class="op">{</span> <span class="st">&quot;The desired std. dev. must be &gt;= 0&quot;</span> <span class="op">}</span></span>
<span id="cb86-12"><a href="ch3StatReview.html#cb86-12" tabindex="-1"></a>            require<span class="op">(!(</span>level <span class="op">&lt;=</span> <span class="fl">0.0</span> <span class="op">||</span> level <span class="op">&gt;=</span> <span class="fl">1.0</span><span class="op">))</span> <span class="op">{</span> <span class="st">&quot;Confidence Level must be (0,1)&quot;</span> <span class="op">}</span></span>
<span id="cb86-13"><a href="ch3StatReview.html#cb86-13" tabindex="-1"></a>            <span class="kw">val</span> <span class="va">a</span> <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> level</span>
<span id="cb86-14"><a href="ch3StatReview.html#cb86-14" tabindex="-1"></a>            <span class="kw">val</span> <span class="va">a2</span> <span class="op">=</span> a <span class="op">/</span> <span class="fl">2.0</span></span>
<span id="cb86-15"><a href="ch3StatReview.html#cb86-15" tabindex="-1"></a>            <span class="kw">val</span> <span class="va">z</span> <span class="op">=</span> Normal<span class="op">.</span>stdNormalInvCDF<span class="op">(</span><span class="fl">1.0</span> <span class="op">-</span> a2<span class="op">)</span></span>
<span id="cb86-16"><a href="ch3StatReview.html#cb86-16" tabindex="-1"></a>            <span class="kw">val</span> <span class="va">m</span> <span class="op">=</span> z <span class="op">*</span> stdDev <span class="op">/</span> desiredHW <span class="op">*</span> <span class="op">(</span>z <span class="op">*</span> stdDev <span class="op">/</span> desiredHW<span class="op">)</span></span>
<span id="cb86-17"><a href="ch3StatReview.html#cb86-17" tabindex="-1"></a>            <span class="kw">return</span> <span class="op">(</span>m <span class="op">+</span> <span class="fl">.5</span><span class="op">).</span>roundToLong<span class="op">()</span></span>
<span id="cb86-18"><a href="ch3StatReview.html#cb86-18" tabindex="-1"></a>        <span class="op">}</span></span></code></pre></div>
<p>In order to use either the <em>normal approximation</em> method or the <em>Student-T iterative</em> method, you must have an initial value for, <span class="math inline">\(s\)</span>, the sample standard deviation. The simplest way to get an initial estimate of <span class="math inline">\(s\)</span> is to make a small initial pilot sample
(e.g. <span class="math inline">\(n_0=5\)</span>). Given a value for <span class="math inline">\(s\)</span> you can then set a desired bound and
use the formulas. The bound is problem and performance measure dependent
and is under your subjective control. You must determine what bound is
reasonable for your given situation. One thing to remember is that the
bound is squared in the denominator for evaluating <span class="math inline">\(n\)</span>. Thus, very small
values of <span class="math inline">\(\epsilon\)</span> can result in very large sample sizes.</p>
<hr />
<div class="example">
<p><span id="exm:ch3ex7" class="example"><strong>Example 3.7  (Determining the Sample Size) </strong></span>Suppose we are required to estimate the output from a simulation so that we are 99% confidence that we are within <span class="math inline">\(\pm 0.1\)</span> of the true population
mean. After taking a pilot sample of size <span class="math inline">\(n=10\)</span>, we have estimated <span class="math inline">\(s=6\)</span>. What is the required sample size?</p>
</div>
<hr />
<p>We will use Equation <a href="ch3StatReview.html#eq:zSampleSize">(3.8)</a> to determine the sample size requirement. For a 99% confidence interval, we have
<span class="math inline">\(\alpha = 0.01\)</span> and <span class="math inline">\(\alpha/2 = 0.005\)</span>. Thus, <span class="math inline">\(z_{1-0.005} = z_{0.995} = 2.5758293064439264\)</span>. Because the margin of error, <span class="math inline">\(\epsilon\)</span> is <span class="math inline">\(0.1\)</span>, we have that,</p>
<p><span class="math display">\[n \geq \left(\dfrac{z_{1-(\alpha/2)}\; s}{\epsilon}\right)^2 = \left(\dfrac{2.5758293064439264 \times 6}{0.1}\right)^2 = 23885.63 \approx 23886\]</span></p>
<p>The following KSL code will easily compute the sample size.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode kt"><code class="sourceCode kotlin"><span id="cb87-1"><a href="ch3StatReview.html#cb87-1" tabindex="-1"></a><span class="kw">fun</span> <span class="fu">main</span><span class="op">()</span> <span class="op">{</span></span>
<span id="cb87-2"><a href="ch3StatReview.html#cb87-2" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">desiredHW</span> <span class="op">=</span> <span class="fl">0.1</span></span>
<span id="cb87-3"><a href="ch3StatReview.html#cb87-3" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">s0</span> <span class="op">=</span> <span class="fl">6.0</span></span>
<span id="cb87-4"><a href="ch3StatReview.html#cb87-4" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">level</span> <span class="op">=</span> <span class="fl">0.99</span></span>
<span id="cb87-5"><a href="ch3StatReview.html#cb87-5" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">n</span> <span class="op">=</span> Statistic<span class="op">.</span>estimateSampleSize<span class="op">(</span></span>
<span id="cb87-6"><a href="ch3StatReview.html#cb87-6" tabindex="-1"></a>        desiredHW <span class="op">=</span> desiredHW<span class="op">,</span></span>
<span id="cb87-7"><a href="ch3StatReview.html#cb87-7" tabindex="-1"></a>        stdDev <span class="op">=</span> s0<span class="op">,</span></span>
<span id="cb87-8"><a href="ch3StatReview.html#cb87-8" tabindex="-1"></a>        level <span class="op">=</span> level</span>
<span id="cb87-9"><a href="ch3StatReview.html#cb87-9" tabindex="-1"></a>    <span class="op">)</span></span>
<span id="cb87-10"><a href="ch3StatReview.html#cb87-10" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;Sample Size Determination&quot;</span><span class="op">)</span></span>
<span id="cb87-11"><a href="ch3StatReview.html#cb87-11" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;desiredHW = </span><span class="ss">$desiredHW</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb87-12"><a href="ch3StatReview.html#cb87-12" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;stdDev = </span><span class="ss">$s0</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb87-13"><a href="ch3StatReview.html#cb87-13" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;Level = </span><span class="ss">$level</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb87-14"><a href="ch3StatReview.html#cb87-14" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;recommended sample size = </span><span class="ss">$n</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb87-15"><a href="ch3StatReview.html#cb87-15" tabindex="-1"></a><span class="op">}</span></span></code></pre></div>
<pre><code>Sample Size Determination
desiredHW = 0.1
stdDev = 6.0
Level = 0.99
recommended sample size = 23886</code></pre>
<p>If the quantity of interest is a proportion, then a different method can
be used. In particular, a <span class="math inline">\(100\times(1 - \alpha)\%\)</span> large sample two sided
confidence interval for a proportion, <span class="math inline">\(p\)</span>, has the following form:</p>
<p><span class="math display" id="eq:propCI">\[\begin{equation}
\hat{p} \pm z_{1-(\alpha/2)} \sqrt{\dfrac{\hat{p}(1 - \hat{p})}{n}}
  \tag{3.9}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\hat{p}\)</span> is the estimate for <span class="math inline">\(p\)</span>. From this, you can determine
the sample size via the following equation:</p>
<p><span class="math display" id="eq:pSampleSize">\[\begin{equation}
n = \left(\dfrac{z_{1-(\alpha/2)}}{\epsilon}\right)^{2} \hat{p}(1 - \hat{p})
  \tag{3.10}
\end{equation}\]</span></p>
<p>Again, a pilot run is necessary for obtaining an initial estimate of <span class="math inline">\(\hat{p}\)</span>, for use in determining the sample size. If no pilot run is
available, then <span class="math inline">\(\hat{p} =0.5\)</span> is often assumed as a worse case approximation.</p>
<p>If you have more than one performance measure of interest, you can use
these sample size techniques for each of your performance measures and
then use the maximum sample size required across the performance
measures. Now, let’s illustrate these methods based on a small simulation.</p>
</div>
<div id="determining-the-sample-size-for-a-monte-carlo-simulation-experiment" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Determining the Sample Size for a Monte Carlo Simulation Experiment<a href="ch3StatReview.html#determining-the-sample-size-for-a-monte-carlo-simulation-experiment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To facilitate some of the calculations related to determining the sample size for a simulation experiment, I have constructed a spreadsheet called <em>SampleSizeDetermination.xlsx</em>, which is found in the book support files for this chapter. You may want to utilize that spreadsheet as you go through this and subsequent sections.</p>
<p>Using a simple example, we will illustrate how to determine the sample size necessary to estimate a quantity of interest with a high level of confidence.</p>
<hr />
<div class="example">
<p><span id="exm:ch3ex8" class="example"><strong>Example 3.8  (Sample Size Example) </strong></span>Suppose that we want to simulate a normally distributed random variable, <span class="math inline">\(X\)</span>, with <span class="math inline">\(E[X] = 10\)</span> and <span class="math inline">\(Var[X] = 16\)</span>. From the simulation, we want to estimate the true population mean with 99 percent confidence for a half-width <span class="math inline">\(\pm 0.50\)</span> margin of error. In addition to estimating the population mean, we want to estimate the probability that the random variable exceeds 8. That is, we want to estimate, <span class="math inline">\(p= P(X&gt;8)\)</span>. We want to be 95% confident that our estimate of <span class="math inline">\(P(X&gt;8)\)</span> has a margin of error of <span class="math inline">\(\pm 0.05\)</span>. What are the sample size requirements needed to meet the desired margins of error?</p>
</div>
<hr />
<p>Using simulation for this example is for illustrative purposes. Naturally, we actually know the true population mean and we can easily compute the <span class="math inline">\(p= P(X&gt;8)\)</span>. for this situation. However, the example will illustrate sample size determination, which is an important planning requirement for simulation experiments.</p>
<p>Let <span class="math inline">\(X\)</span> represent the unknown random variable of interest. Then, we are
interested in estimating <span class="math inline">\(E[X]=\mu\)</span> and <span class="math inline">\(p = P(X &gt; 8)\)</span>. To estimate
these quantities, we generate a random sample, <span class="math inline">\((X_1,X_2,...,X_n)\)</span>. <span class="math inline">\(E[X]\)</span> can be
estimated using <span class="math inline">\(\bar{X}\)</span>. To estimate a probability it is useful to define an indicator variable. An indicator variable has the value 1 if the condition associated with the probability is true and has the value 0 if it is false. To estimate <span class="math inline">\(p\)</span>, define the following indicator
variable:</p>
<p><span class="math display">\[
Y_i =
   \begin{cases}
     1 &amp; X_i &gt; 8\\
     0 &amp; X_i \leq 8 \\
  \end{cases}
\]</span>
This definition of the indicator variable <span class="math inline">\(Y_i\)</span> allows <span class="math inline">\(\bar{Y}\)</span> to be
used to estimate <span class="math inline">\(p\)</span>. Recall the definition of the sample average
<span class="math inline">\(\bar{Y}\)</span>. Since <span class="math inline">\(Y_{i}\)</span> is a <span class="math inline">\(1\)</span> only if <span class="math inline">\(X_i &gt; 8\)</span>, then the
<span class="math inline">\(\sum \nolimits_{i=1}^{n} Y_{i}\)</span> simply adds up the number of <span class="math inline">\(1\)</span>’s in
the sample. Thus, <span class="math inline">\(\sum\nolimits_{i=1}^{n} Y_{i}\)</span> represents the count
of the number of times the event <span class="math inline">\(X_i &gt; 8\)</span> occurred in the sample. Call
this <span class="math inline">\(\#\lbrace X_i &gt; 8\rbrace\)</span>. The ratio of the number of times an
event occurred to the total number of possible occurrences represents
the proportion. Thus, an estimator for <span class="math inline">\(p\)</span> is:</p>
<p><span class="math display">\[
\hat{p} = \bar{Y} = \frac{1}{n}\sum_{i=1}^{n}Y_i = \frac{\#\lbrace X_i  &gt; 8\rbrace}{n}
\]</span>
Therefore, computing the average of an indicator variable will estimate
the desired probability. The code for this situation is quite simple:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode kt"><code class="sourceCode kotlin"><span id="cb89-1"><a href="ch3StatReview.html#cb89-1" tabindex="-1"></a><span class="kw">fun</span> <span class="fu">main</span><span class="op">()</span> <span class="op">{</span></span>
<span id="cb89-2"><a href="ch3StatReview.html#cb89-2" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">rv</span> <span class="op">=</span> NormalRV<span class="op">(</span><span class="fl">10.0</span><span class="op">,</span> <span class="fl">16.0</span><span class="op">,</span> streamNum <span class="op">=</span> <span class="dv">3</span><span class="op">)</span></span>
<span id="cb89-3"><a href="ch3StatReview.html#cb89-3" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">estimateX</span> <span class="op">=</span> Statistic<span class="op">(</span><span class="st">&quot;Estimated X&quot;</span><span class="op">)</span></span>
<span id="cb89-4"><a href="ch3StatReview.html#cb89-4" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">estOfProb</span> <span class="op">=</span> Statistic<span class="op">(</span><span class="st">&quot;Pr(X&gt;8)&quot;</span><span class="op">)</span></span>
<span id="cb89-5"><a href="ch3StatReview.html#cb89-5" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">r</span> <span class="op">=</span> StatisticReporter<span class="op">(</span>mutableListOf<span class="op">(</span>estOfProb<span class="op">,</span> estimateX<span class="op">))</span></span>
<span id="cb89-6"><a href="ch3StatReview.html#cb89-6" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">n0</span> <span class="op">=</span> <span class="dv">20</span> <span class="co">// sample size</span></span>
<span id="cb89-7"><a href="ch3StatReview.html#cb89-7" tabindex="-1"></a>    <span class="cf">for</span> <span class="op">(</span>i <span class="kw">in</span> <span class="fl">1.</span><span class="op">.</span>n0<span class="op">)</span> <span class="op">{</span></span>
<span id="cb89-8"><a href="ch3StatReview.html#cb89-8" tabindex="-1"></a>        <span class="kw">val</span> <span class="va">x</span> <span class="op">=</span> rv<span class="op">.</span>value</span>
<span id="cb89-9"><a href="ch3StatReview.html#cb89-9" tabindex="-1"></a>        estimateX<span class="op">.</span>collect<span class="op">(</span>x<span class="op">)</span></span>
<span id="cb89-10"><a href="ch3StatReview.html#cb89-10" tabindex="-1"></a>        estOfProb<span class="op">.</span>collect<span class="op">(</span>x <span class="op">&gt;</span> <span class="dv">8</span><span class="op">)</span></span>
<span id="cb89-11"><a href="ch3StatReview.html#cb89-11" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb89-12"><a href="ch3StatReview.html#cb89-12" tabindex="-1"></a>    println<span class="op">(</span>r<span class="op">.</span>halfWidthSummaryReport<span class="op">())</span></span>
<span id="cb89-13"><a href="ch3StatReview.html#cb89-13" tabindex="-1"></a><span class="op">}</span></span></code></pre></div>
<p>In the code, an instance of Statistic is used to observe values of the quantity <span class="math inline">\((x &gt; 8)\)</span>. This quantity is actually a logical condition which will evaluate to true (1) or false (0) given the value of <span class="math inline">\(x\)</span>. Thus, the Statistic will be recording observations of 1’s and 0’s. Because the Statistic computes the average of the values that it “collects”, we will get an estimate of the probability. Thus, the quantity, <span class="math inline">\((x &gt; 8)\)</span> is an indicator variable for the desired event. Using a Statistic to estimate a probability in this manner is quite effective.</p>
<p>Now, in more realistic simulation situations, we would not know the true population mean and variance. Thus, in solving this problem, we will ignore that information. To apply the previously discussed sample size determination methods, we need estimates of <span class="math inline">\(\sigma = \sqrt{Var[X]}\)</span> and <span class="math inline">\(p = P(X&gt;8)\)</span>. In order to get estimates of these quantities, we need to run our simulation experiment; however, in order to run our simulation experiment, we need to know how many observations to make. This is quite a catch-22 situation!</p>
<p>To proceed, we need to run our simulation model for a pilot experiment. From a small number of samples (called a pilot experiment, pilot run or pilot study), we will estimate <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(p = P(X&gt;8)\)</span> and then use those estimates to determine how many samples we need to meet the desired margins of error. We will then re-run the simulation using the recommended sample size.</p>
<p>The natural question to ask is how big should your pilot sample be? In general, this depends on how much it costs for you to collect the sample. Within a simulation experiment context, generally, cost translates into how long your simulation model takes to execute. For this small problem, the execution time is trivial, but for large and complex simulation models the execution time may be in hours or even days. A general rule of thumb is between 10 and 30 observations. For this example, we will use an initial pilot sample size, <span class="math inline">\(n_0 = 20\)</span>.</p>
<p>Running the model for the 20 replications yields the following results.</p>
<table>
<caption><span id="tab:exResults">Table 3.1: </span> Simulation results for <span class="math inline">\(n_0 = 20\)</span> replications</caption>
<thead>
<tr>
<th>Performance Measures</th>
<th>Average</th>
<th>95% Half-Width</th>
</tr>
</thead>
<tbody>
<tr>
<td>Pr(X&gt;8)</td>
<td>0.80</td>
<td>0.1921</td>
</tr>
<tr>
<td>Estimated X</td>
<td>12.2484</td>
<td>2.2248</td>
</tr>
</tbody>
</table>
<p>Notice that the confidence interval for the true mean is <span class="math inline">\((10.0236,14.4732)\)</span> with a half-width of <span class="math inline">\(2.2248\)</span>, which exceeds the desired margin of error, <span class="math inline">\(\epsilon = 0.5\)</span>. Notice also that this particular confidence interval happens to not contain the true mean <span class="math inline">\(E[X] = 10\)</span>. To determine the sample size so that we get a half-width that is less than <span class="math inline">\(\epsilon = 0.1\)</span> with 99% confidence, we can use Equation <a href="ch3StatReview.html#eq:zSampleSize">(3.8)</a>. In order to do this, we must first have an estimate of the sample standard deviation, <span class="math inline">\(s\)</span>. Since Table <a href="ch3StatReview.html#tab:exResults">3.1</a> reports a half-width for a 95% confidence interval, we need to use Equation <a href="ch3StatReview.html#eq:hw">(3.6)</a> and solve for <span class="math inline">\(s\)</span> in terms of <span class="math inline">\(h\)</span>. Rearranging Equation <a href="ch3StatReview.html#eq:hw">(3.6)</a> yields,</p>
<p><span class="math display" id="eq:sInTermsOfh">\[\begin{equation}
s = \dfrac{h\sqrt{n}}{t_{1-(\alpha/2), n-1}}
  \tag{3.11}
\end{equation}\]</span></p>
<p>Using the results from Table <a href="ch3StatReview.html#tab:exResults">3.1</a> and <span class="math inline">\(\alpha = 0.05\)</span> in Equation <a href="ch3StatReview.html#eq:sInTermsOfh">(3.11)</a> yields,</p>
<p><span class="math display">\[
s_0 = \dfrac{h\sqrt{n_0}}{t_{1-(\alpha/2), n_0-1}} = \dfrac{2.2248\sqrt{20}}{t_{0.975, 19}}= \dfrac{2.2248\sqrt{20}}{2.093024}=4.7536998
\]</span></p>
<p>Now, we can use Equation <a href="ch3StatReview.html#eq:zSampleSize">(3.8)</a> to determine the sample size requirement. For a 99% confidence interval, we have
<span class="math inline">\(\alpha = 0.01\)</span> and <span class="math inline">\(\alpha/2 = 0.005\)</span>. Thus, <span class="math inline">\(z_{0.995} = 2.576\)</span>. Because the margin of error, <span class="math inline">\(\epsilon\)</span> is <span class="math inline">\(0.5,\)</span> we have that,</p>
<p><span class="math display">\[n \geq \left(\dfrac{z_{1-(\alpha/2)}\; s}{\epsilon}\right)^2 = \left(\dfrac{2.5758293064439264 \times 4.7536998}{0.5}\right)^2 = 599.73 \approx 600\]</span>
To determine the sample size for estimating <span class="math inline">\(p=P(X&gt;8)\)</span> with 95% confidence to <span class="math inline">\(\pm 0.1\)</span>, we can use Equation <a href="ch3StatReview.html#eq:pSampleSize">(3.10)</a></p>
<p><span class="math display">\[
n = \left(\dfrac{z_{1-(\alpha/2)}}{\epsilon}\right)^{2} \hat{p}(1 - \hat{p})=\left(\dfrac{z_{0.975}}{0.05}\right)^{2} (0.80)(1 - 0.80)=\left(\dfrac{1.96}{0.05}\right)^{2} (0.80)(0.20) = 245.86 \approx 246
\]</span></p>
<p>All of these calculations can be easily accomplished using Kotlin code as follows:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode kt"><code class="sourceCode kotlin"><span id="cb90-1"><a href="ch3StatReview.html#cb90-1" tabindex="-1"></a><span class="kw">fun</span> <span class="fu">main</span><span class="op">()</span> <span class="op">{</span></span>
<span id="cb90-2"><a href="ch3StatReview.html#cb90-2" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">rv</span> <span class="op">=</span> NormalRV<span class="op">(</span><span class="fl">10.0</span><span class="op">,</span> <span class="fl">16.0</span><span class="op">,</span> streamNum <span class="op">=</span> <span class="dv">3</span><span class="op">)</span></span>
<span id="cb90-3"><a href="ch3StatReview.html#cb90-3" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">estimateX</span> <span class="op">=</span> Statistic<span class="op">(</span><span class="st">&quot;Estimated X&quot;</span><span class="op">)</span></span>
<span id="cb90-4"><a href="ch3StatReview.html#cb90-4" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">estOfProb</span> <span class="op">=</span> Statistic<span class="op">(</span><span class="st">&quot;Pr(X&gt;8)&quot;</span><span class="op">)</span></span>
<span id="cb90-5"><a href="ch3StatReview.html#cb90-5" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">r</span> <span class="op">=</span> StatisticReporter<span class="op">(</span>mutableListOf<span class="op">(</span>estOfProb<span class="op">,</span> estimateX<span class="op">))</span></span>
<span id="cb90-6"><a href="ch3StatReview.html#cb90-6" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">n0</span> <span class="op">=</span> <span class="dv">20</span> <span class="co">// sample size</span></span>
<span id="cb90-7"><a href="ch3StatReview.html#cb90-7" tabindex="-1"></a>    <span class="cf">for</span> <span class="op">(</span>i <span class="kw">in</span> <span class="fl">1.</span><span class="op">.</span>n0<span class="op">)</span> <span class="op">{</span></span>
<span id="cb90-8"><a href="ch3StatReview.html#cb90-8" tabindex="-1"></a>        <span class="kw">val</span> <span class="va">x</span> <span class="op">=</span> rv<span class="op">.</span>value</span>
<span id="cb90-9"><a href="ch3StatReview.html#cb90-9" tabindex="-1"></a>        estimateX<span class="op">.</span>collect<span class="op">(</span>x<span class="op">)</span></span>
<span id="cb90-10"><a href="ch3StatReview.html#cb90-10" tabindex="-1"></a>        estOfProb<span class="op">.</span>collect<span class="op">(</span>x <span class="op">&gt;</span> <span class="dv">8</span><span class="op">)</span></span>
<span id="cb90-11"><a href="ch3StatReview.html#cb90-11" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb90-12"><a href="ch3StatReview.html#cb90-12" tabindex="-1"></a>    println<span class="op">(</span>r<span class="op">.</span>halfWidthSummaryReport<span class="op">())</span></span>
<span id="cb90-13"><a href="ch3StatReview.html#cb90-13" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">desiredHW</span> <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb90-14"><a href="ch3StatReview.html#cb90-14" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">s0</span> <span class="op">=</span> estimateX<span class="op">.</span>standardDeviation</span>
<span id="cb90-15"><a href="ch3StatReview.html#cb90-15" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">level</span> <span class="op">=</span> <span class="fl">0.99</span></span>
<span id="cb90-16"><a href="ch3StatReview.html#cb90-16" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">n</span> <span class="op">=</span> Statistic<span class="op">.</span>estimateSampleSize<span class="op">(</span></span>
<span id="cb90-17"><a href="ch3StatReview.html#cb90-17" tabindex="-1"></a>        desiredHW <span class="op">=</span> desiredHW<span class="op">,</span></span>
<span id="cb90-18"><a href="ch3StatReview.html#cb90-18" tabindex="-1"></a>        stdDev <span class="op">=</span> s0<span class="op">,</span></span>
<span id="cb90-19"><a href="ch3StatReview.html#cb90-19" tabindex="-1"></a>        level <span class="op">=</span> level</span>
<span id="cb90-20"><a href="ch3StatReview.html#cb90-20" tabindex="-1"></a>    <span class="op">)</span></span>
<span id="cb90-21"><a href="ch3StatReview.html#cb90-21" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;Sample Size Determination&quot;</span><span class="op">)</span></span>
<span id="cb90-22"><a href="ch3StatReview.html#cb90-22" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;desiredHW = </span><span class="ss">$desiredHW</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb90-23"><a href="ch3StatReview.html#cb90-23" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;stdDev = </span><span class="ss">$s0</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb90-24"><a href="ch3StatReview.html#cb90-24" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;Level = </span><span class="ss">$level</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb90-25"><a href="ch3StatReview.html#cb90-25" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;recommended sample size = </span><span class="ss">$n</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb90-26"><a href="ch3StatReview.html#cb90-26" tabindex="-1"></a>    println<span class="op">()</span></span>
<span id="cb90-27"><a href="ch3StatReview.html#cb90-27" tabindex="-1"></a>    <span class="kw">val</span> <span class="va">m</span> <span class="op">=</span> Statistic<span class="op">.</span>estimateProportionSampleSize<span class="op">(</span></span>
<span id="cb90-28"><a href="ch3StatReview.html#cb90-28" tabindex="-1"></a>        desiredHW <span class="op">=</span> <span class="fl">0.05</span><span class="op">,</span></span>
<span id="cb90-29"><a href="ch3StatReview.html#cb90-29" tabindex="-1"></a>        pEst <span class="op">=</span> estOfProb<span class="op">.</span>average<span class="op">,</span></span>
<span id="cb90-30"><a href="ch3StatReview.html#cb90-30" tabindex="-1"></a>        level <span class="op">=</span> <span class="fl">0.95</span></span>
<span id="cb90-31"><a href="ch3StatReview.html#cb90-31" tabindex="-1"></a>    <span class="op">)</span></span>
<span id="cb90-32"><a href="ch3StatReview.html#cb90-32" tabindex="-1"></a>    println<span class="op">(</span><span class="st">&quot;Recommended sample size for proportion = </span><span class="ss">$m</span><span class="st">&quot;</span><span class="op">)</span></span>
<span id="cb90-33"><a href="ch3StatReview.html#cb90-33" tabindex="-1"></a><span class="op">}</span></span></code></pre></div>
<p>The results match the values computed from the equations.</p>
<pre><code>Sample Size Determination
desiredHW = 0.5
stdDev = 4.753707020199372
Level = 0.99
recommended sample size = 600
Recommended sample size for proportion = 246</code></pre>
<p>By using the maximum of <span class="math inline">\(\max{(246, 600)=600}\)</span>, we can re-run the simulation for this number of replications. Doing so, yields,</p>
<table>
<caption><span id="tab:exResultsn609">Table 3.2: </span> Simulation Results for <span class="math inline">\(n=600\)</span> Replications</caption>
<thead>
<tr>
<th>Performance Measures</th>
<th>Average</th>
<th>95% Half-Width</th>
</tr>
</thead>
<tbody>
<tr>
<td>Pr(X&gt;8)</td>
<td>0.7117</td>
<td>0.0363</td>
</tr>
<tr>
<td>Estimated X</td>
<td>10.2712</td>
<td>0.3284</td>
</tr>
</tbody>
</table>
<p>As can be seen in Table <a href="ch3StatReview.html#tab:exResultsn609">3.2</a>, the half-width values meet the desire margins of error. It may be possible that the margins of error might not be met. This suggests that more than <span class="math inline">\(n = 600\)</span> observations is needed to meet the margin of error criteria. Equation <a href="ch3StatReview.html#eq:zSampleSize">(3.8)</a> and Equation <a href="ch3StatReview.html#eq:pSampleSize">(3.10)</a> are only <em>approximations</em> and based on a pilot sample. Thus, if there was considerable sampling error associated
with the pilot sample, the approximations may be inadequate.</p>
<p>As can be noted from this example in order to apply the normal approximation method for determining the sample size based on the pilot run, we need to compute the initial sample standard deviation, <span class="math inline">\(s_0\)</span>, from the initial reported half-width, <span class="math inline">\(h\)</span>. This requires the use of Equation <a href="ch3StatReview.html#eq:sInTermsOfh">(3.11)</a> to first compute the value of <span class="math inline">\(s\)</span> from <span class="math inline">\(h\)</span>. We can avoid this calculation by using the <em>half-width ratio</em> method for determining the sample size.</p>
<p>Let <span class="math inline">\(h_0\)</span> be the initial value for the half-width from the pilot run of
<span class="math inline">\(n_0\)</span> replications. Then, rewriting Equation <a href="ch3StatReview.html#eq:hw">(3.6)</a> in terms of the pilot data yields:</p>
<p><span class="math display">\[
h_0 = t_{1-(\alpha/2), n_0 - 1} \dfrac{s_0}{\sqrt{n_0}}
\]</span>
Solving for <span class="math inline">\(n_0\)</span> yields:</p>
<p><span class="math display" id="eq:nNottsh">\[\begin{equation}
n_0 = t_{1-(\alpha/2), n_0 -1}^{2} \dfrac{s_{0}^{2}}{h_{0}^{2}}
  \tag{3.12}
\end{equation}\]</span></p>
<p>Similarly for any <span class="math inline">\(n\)</span>, we have:</p>
<p><span class="math display" id="eq:ntsh">\[\begin{equation}
n = t_{1-(\alpha/2), n-1}^{2} \dfrac{s^{2}}{h^{2}}
  \tag{3.13}
\end{equation}\]</span></p>
<p>Taking the ratio of <span class="math inline">\(n_0\)</span> to <span class="math inline">\(n\)</span> (Equations <a href="ch3StatReview.html#eq:nNottsh">(3.12)</a> and <a href="ch3StatReview.html#eq:ntsh">(3.13)</a>) and assuming
that <span class="math inline">\(t_{1-(\alpha/2), n-1}\)</span> is approximately equal to
<span class="math inline">\(t_{1-(\alpha/2), n_0 - 1}\)</span> and <span class="math inline">\(s^2\)</span> is approximately equal to <span class="math inline">\(s_0^2\)</span>,
yields,</p>
<p><span class="math display">\[n \cong n_0 \dfrac{h_0^2}{h^2} = n_0 \left(\frac{h_0}{h}\right)^2\]</span></p>
<p>This is the half-width ratio equation.</p>
<p><span class="math display" id="eq:hwratio">\[\begin{equation}
n \geq n_0 \left(\frac{h_0}{h}\right)^2
  \tag{3.14}
\end{equation}\]</span></p>
<p>The issue that we face when applying Equation <a href="ch3StatReview.html#eq:hwratio">(3.14)</a> is that Table <a href="ch3StatReview.html#tab:exResults">3.1</a> only reports the
95% confidence interval half-width. Thus, to apply Equation <a href="ch3StatReview.html#eq:hwratio">(3.14)</a> the value of <span class="math inline">\(h_0\)</span> will be based on an <span class="math inline">\(\alpha = 0.05\)</span>. If the desired half-width, <span class="math inline">\(h\)</span>, is required for a different confidence level, e.g. a 99% confidence interval, then you must first translate <span class="math inline">\(h_0\)</span> to be based on the desired confidence level or set the confidence level for the <code>StatisticalReporter</code> to be 99%. To compute the 95% half-width from Table <a href="ch3StatReview.html#tab:exResults">3.1</a>, you can compute <span class="math inline">\(s\)</span> from Equation <a href="ch3StatReview.html#eq:sInTermsOfh">(3.11)</a> and then recomputing the actual half-width, <span class="math inline">\(h\)</span>, for the desired confidence level.</p>
<p>Using the results from Table <a href="ch3StatReview.html#tab:exResults">3.1</a> and <span class="math inline">\(\alpha = 0.05\)</span> in Equation <a href="ch3StatReview.html#eq:sInTermsOfh">(3.11)</a> we already know that <span class="math inline">\(s_0 = 4.7536998\)</span> for a 95% confidence interval. Thus, for a 99% confidence interval, where <span class="math inline">\(\alpha = 0.01\)</span> and <span class="math inline">\(\alpha/2 = 0.005\)</span>, we have:</p>
<p><span class="math display">\[
h_0 = t_{1-(\alpha/2), n_0-1} \dfrac{s_0}{\sqrt{n_0}}= t_{0.995, 19}\dfrac{4.7536998}{\sqrt{20}}=2.861\dfrac{4.7536998}{\sqrt{20}}=3.041127
\]</span>
Now, we can apply Equation <a href="ch3StatReview.html#eq:hwratio">(3.14)</a> to this problem with the desire half-width bound <span class="math inline">\(\epsilon = 0.5 = h\)</span>:</p>
<p><span class="math display">\[
n \geq n_0 \left(\frac{h_0}{h}\right)^2=20\left(\frac{3.041127}{h}\right)^2=20\left(\frac{3.041127}{0.5}\right)^2=739.87 \cong 740
\]</span></p>
<p>We see that for this pilot sample, the half-width ratio method recommends a substantially larger sample size, <span class="math inline">\(740\)</span> versus <span class="math inline">\(600\)</span>. In practice, the half-width ratio method tends to be conservative by recommending a larger sample size. We will see another example of these methods within the next section.</p>
<p>Based on these examples, you should have a basic understanding of how a
simulation experiment can be performed to meet a desired margin of error. In general, simulation models are much more interesting than this simple example.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ssMC.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="craps.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
